# -*- coding: utf-8 -*-
"""Hand-maintained, layout-based UI for the capture dialog.

Originally generated by pyuic5 from ``assets/capture.ui`` (now obsolete).
Rewritten to use nested layouts so text is never clipped and the dialog
resizes naturally with the Windows system font/DPI.
"""

from PyQt5 import QtCore, QtWidgets


def _label(parent: QtWidgets.QWidget, text: str) -> QtWidgets.QLabel:
    lb = QtWidgets.QLabel(text, parent)
    lb.setSizePolicy(
        QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
    )
    return lb


class Ui_Dialog(object):
    def setupUi(self, Dialog: QtWidgets.QDialog) -> None:
        Dialog.setObjectName("Dialog")
        Dialog.setWindowTitle("Ebook Capture")

        root = QtWidgets.QVBoxLayout(Dialog)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(8)

        # ------------------------------------------------------------------
        # Options
        # ------------------------------------------------------------------
        self.gb_options = QtWidgets.QGroupBox("Options", Dialog)
        self.gb_options.setObjectName("gb_options")
        grid = QtWidgets.QGridLayout(self.gb_options)
        grid.setHorizontalSpacing(8)
        grid.setVerticalSpacing(6)
        grid.setColumnStretch(1, 3)
        grid.setColumnStretch(3, 2)

        row = 0
        self.lb_title = _label(self.gb_options, "Title")
        self.le_title = QtWidgets.QLineEdit(self.gb_options)
        grid.addWidget(self.lb_title, row, 0)
        grid.addWidget(self.le_title, row, 1, 1, 3)

        row += 1
        self.lb_folder = _label(self.gb_options, "Folder")
        self.le_folder = QtWidgets.QLineEdit(self.gb_options)
        self.btn_browse = QtWidgets.QPushButton("Browse…", self.gb_options)
        self.btn_browse.setAutoDefault(False)
        folder_box = QtWidgets.QHBoxLayout()
        folder_box.setSpacing(6)
        folder_box.addWidget(self.le_folder, 1)
        folder_box.addWidget(self.btn_browse)
        grid.addWidget(self.lb_folder, row, 0)
        grid.addLayout(folder_box, row, 1, 1, 3)

        row += 1
        self.lb_reader = _label(self.gb_options, "Reader")
        self.cb_reader = QtWidgets.QComboBox(self.gb_options)
        grid.addWidget(self.lb_reader, row, 0)
        grid.addWidget(self.cb_reader, row, 1, 1, 3)

        row += 1
        self.lb_next = _label(self.gb_options, "Next key")
        self.cb_next = QtWidgets.QComboBox(self.gb_options)
        self.lb_interval = _label(self.gb_options, "Delay (sec)")
        self.sb_delay = QtWidgets.QDoubleSpinBox(self.gb_options)
        grid.addWidget(self.lb_next, row, 0)
        grid.addWidget(self.cb_next, row, 1)
        grid.addWidget(self.lb_interval, row, 2)
        grid.addWidget(self.sb_delay, row, 3)

        row += 1
        self.lb_key_delivery = _label(self.gb_options, "Key send")
        self.cb_key_delivery = QtWidgets.QComboBox(self.gb_options)
        self.lb_focus_clicks = _label(self.gb_options, "Focus clicks")
        self.sb_focus_clicks = QtWidgets.QSpinBox(self.gb_options)
        grid.addWidget(self.lb_key_delivery, row, 0)
        grid.addWidget(self.cb_key_delivery, row, 1)
        grid.addWidget(self.lb_focus_clicks, row, 2)
        grid.addWidget(self.sb_focus_clicks, row, 3)

        row += 1
        self.lb_output = _label(self.gb_options, "Output")
        self.cb_output_mode = QtWidgets.QComboBox(self.gb_options)
        self.lb_ocr_lang = _label(self.gb_options, "OCR lang")
        self.cb_ocr_lang_pri = QtWidgets.QComboBox(self.gb_options)
        grid.addWidget(self.lb_output, row, 0)
        grid.addWidget(self.cb_output_mode, row, 1)
        grid.addWidget(self.lb_ocr_lang, row, 2)
        grid.addWidget(self.cb_ocr_lang_pri, row, 3)

        row += 1
        self.lb_assemble_style = _label(self.gb_options, "Markdown")
        self.cb_assemble_style = QtWidgets.QComboBox(self.gb_options)
        grid.addWidget(self.lb_assemble_style, row, 0)
        grid.addWidget(self.cb_assemble_style, row, 1, 1, 3)

        row += 1
        self.chk_resume = QtWidgets.QCheckBox(
            "Resume (skip done pages)", self.gb_options
        )
        self.lb_force_phase = _label(self.gb_options, "Force")
        self.cb_force_phase = QtWidgets.QComboBox(self.gb_options)
        grid.addWidget(self.chk_resume, row, 0, 1, 2)
        grid.addWidget(self.lb_force_phase, row, 2)
        grid.addWidget(self.cb_force_phase, row, 3)

        row += 1
        self.lb_win_backend = _label(self.gb_options, "Backend")
        self.cb_window_backend = QtWidgets.QComboBox(self.gb_options)
        self.chk_client_rect = QtWidgets.QCheckBox(
            "Client area only", self.gb_options
        )
        self.chk_hide_cursor = QtWidgets.QCheckBox("Hide cursor", self.gb_options)
        flags_box = QtWidgets.QHBoxLayout()
        flags_box.setSpacing(10)
        flags_box.addWidget(self.chk_client_rect)
        flags_box.addWidget(self.chk_hide_cursor)
        flags_box.addStretch(1)
        grid.addWidget(self.lb_win_backend, row, 0)
        grid.addWidget(self.cb_window_backend, row, 1)
        grid.addLayout(flags_box, row, 2, 1, 2)

        row += 1
        self.btn_save = QtWidgets.QPushButton("Save Options", self.gb_options)
        self.btn_load = QtWidgets.QPushButton("Load Options", self.gb_options)
        for b in (self.btn_save, self.btn_load):
            b.setAutoDefault(False)
        opt_btn_box = QtWidgets.QHBoxLayout()
        opt_btn_box.setSpacing(6)
        opt_btn_box.addWidget(self.btn_save)
        opt_btn_box.addWidget(self.btn_load)
        opt_btn_box.addStretch(1)
        grid.addLayout(opt_btn_box, row, 0, 1, 4)

        root.addWidget(self.gb_options)

        # ------------------------------------------------------------------
        # Target window & capture area
        # ------------------------------------------------------------------
        self.gb_capture_target = QtWidgets.QGroupBox(
            "Target window && capture area", Dialog
        )
        self.gb_capture_target.setObjectName("gb_capture_target")
        tgrid = QtWidgets.QGridLayout(self.gb_capture_target)
        tgrid.setHorizontalSpacing(8)
        tgrid.setVerticalSpacing(6)

        self.cb_region_preset = QtWidgets.QComboBox(self.gb_capture_target)
        tgrid.addWidget(self.cb_region_preset, 0, 0, 1, 6)

        self.btn_refresh_windows = QtWidgets.QPushButton(
            "Refresh windows", self.gb_capture_target
        )
        self.btn_refresh_windows.setAutoDefault(False)
        self.cb_target_window = QtWidgets.QComboBox(self.gb_capture_target)
        self.cb_target_window.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        tgrid.addWidget(self.btn_refresh_windows, 1, 0, 1, 2)
        tgrid.addWidget(self.cb_target_window, 1, 2, 1, 4)

        self.lb_start_page = _label(self.gb_capture_target, "Start page #")
        self.sb_start_page = QtWidgets.QSpinBox(self.gb_capture_target)
        self.lb_page_count = _label(self.gb_capture_target, "Page count")
        self.sb_page_count = QtWidgets.QSpinBox(self.gb_capture_target)
        self.btn_region = QtWidgets.QPushButton("Region…", self.gb_capture_target)
        self.btn_region.setAutoDefault(False)
        tgrid.addWidget(self.lb_start_page, 2, 0)
        tgrid.addWidget(self.sb_start_page, 2, 1)
        tgrid.addWidget(self.lb_page_count, 2, 2)
        tgrid.addWidget(self.sb_page_count, 2, 3)
        tgrid.addWidget(self.btn_region, 2, 5)
        tgrid.setColumnStretch(4, 1)

        root.addWidget(self.gb_capture_target)

        # ------------------------------------------------------------------
        # Progress
        # ------------------------------------------------------------------
        self.gb_progress = QtWidgets.QGroupBox("Progress", Dialog)
        self.gb_progress.setObjectName("gb_progress")
        pbox = QtWidgets.QVBoxLayout(self.gb_progress)
        pbox.setSpacing(6)

        self.pte_status = QtWidgets.QPlainTextEdit(self.gb_progress)
        self.pte_status.setReadOnly(True)
        self.pte_status.setMinimumHeight(72)
        self.pte_status.setMaximumHeight(120)
        pbox.addWidget(self.pte_status)

        ctrl_box = QtWidgets.QHBoxLayout()
        ctrl_box.setSpacing(6)
        self.pb_progress = QtWidgets.QProgressBar(self.gb_progress)
        self.pb_progress.setValue(0)
        self.lb_time = QtWidgets.QLabel("Ready", self.gb_progress)
        self.lb_time.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter
        )
        self.btn_assemble = QtWidgets.QPushButton("Assemble MD", self.gb_progress)
        self.btn_start = QtWidgets.QPushButton("Start", self.gb_progress)
        self.btn_cancel = QtWidgets.QPushButton("Cancel", self.gb_progress)
        for b in (self.btn_assemble, self.btn_start, self.btn_cancel):
            b.setAutoDefault(False)
        self.btn_start.setDefault(True)
        ctrl_box.addWidget(self.pb_progress, 1)
        ctrl_box.addWidget(self.lb_time)
        ctrl_box.addWidget(self.btn_assemble)
        ctrl_box.addWidget(self.btn_start)
        ctrl_box.addWidget(self.btn_cancel)
        pbox.addLayout(ctrl_box)

        self.gv_preview = QtWidgets.QGraphicsView(self.gb_progress)
        self.gv_preview.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        pbox.addWidget(self.gv_preview, 1)

        root.addWidget(self.gb_progress, 1)

        # Long item texts (window titles, presets) must not force a huge
        # minimum dialog width — let combos elide instead of expanding.
        for combo in (
            self.cb_reader,
            self.cb_next,
            self.cb_key_delivery,
            self.cb_output_mode,
            self.cb_ocr_lang_pri,
            self.cb_assemble_style,
            self.cb_force_phase,
            self.cb_window_backend,
            self.cb_region_preset,
            self.cb_target_window,
        ):
            combo.setSizeAdjustPolicy(
                QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon
            )
            combo.setMinimumContentsLength(8)

        QtCore.QMetaObject.connectSlotsByName(Dialog)
